rbac:
  clusterRole:
    name: github-releases-monitor-role
  clusterRoleBinding:
    name: github-releases-monitor-binding
  serviceAccount:
    name: default
    namespace: default

controllerManager:
  replicas: 3
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    image:
      repository: anu398/cve-operator
      tag: latest
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
      PROCESS_IMAGE: "anu398/cveprocessor:032"
  serviceAccount:
    annotations: {}
  kubernetesClusterDomain: "cluster.local"

metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP

kafka:
  username: "team16"
  password: "password"
  broker1: "kafka-controller-0.kafka-controller-headless.n2.svc.cluster.local:9092"
  broker2: "kafka-controller-1.kafka-controller-headless.n2.svc.cluster.local:9092"
  broker3: "kafka-controller-2.kafka-controller-headless.n2.svc.cluster.local:9092"
  topic: "cve"

namespace: op

processor:
  image: "anu398/cveprocessor:032"

networkPolicy:
  controlPlaneLabel: controller-manager
  egress:
    cidr: 0.0.0.0/0
    port: 443

secrets: 
  myregistrykey:
    dockerconfigjson: "eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhbnUzOTgiLCJwYXNzd29yZCI6ImRvY2tlcl9wYXNzd29yZCIsImVtYWlsIjoic29tZW9uZUBleGFtcGxlLmNvbSIsImF1dGgiOiJiYXNlNjRfZW5jb2RlZF9hdXRoX3Rva2VuIn19fQ=="
  imagePullSecrets:
    - name: myregistrykey

networkPolicy:
  name: network-policy
  ingressPorts:
    - 8081
    - 8443
  egressCIDR: 0.0.0.0/0
  egressPort: 443
