apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-controller-manager-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helm-cve-operator.fullname" . }}-controller-manager
  minReplicas: {{ .Values.controllerManager.hpa.minReplicas }}
  maxReplicas: {{ .Values.controllerManager.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.controllerManager.hpa.targetCPUUtilizationPercentage }}
