apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-manager-role
  labels:
    {{- include "helm-cve-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - webapp.cyse7125-su24-team16
  resources:
  - githubreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.cyse7125-su24-team16
  resources:
  - githubreleasesmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.cyse7125-su24-team16
  resources:
  - githubreleasesmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.cyse7125-su24-team16
  resources:
  - githubreleasesmonitors/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.cyse7125-su24-team16
  resources:
  - githubreleases/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.cyse7125-su24-team16
  resources:
  - githubreleases/finalizers
  verbs:
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "helm-cve-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "helm-cve-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: 'controller-manager-sa'
  namespace: '{{ .Values.namespace }}'