apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}  
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: n2 
    - ipBlock:
        cidr: 0.0.0.0/0 

