apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helm-cve-operator.fullname" . }}-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      control-plane: {{ .Values.networkPolicy.controlPlaneLabel }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.egress.cidr }}
    ports:
    - protocol: TCP
      port: {{ .Values.networkPolicy.egress.port | int }}
