apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: op-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.controllerManager.pdb.minAvailable }}
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/instance: op
      app.kubernetes.io/name: helm-cve-operator
